import dts from "rollup-plugin-dts";

export default {
  input: "./dist/src/index.d.ts", // Path to the main .d.ts file generated by TypeScript
  output: {
    file: "./dist/bundle.d.ts", // The flattened declaration file
    format: "es",
  },
  plugins: [dts()],
};
